/***********************************************************************************************************
 * Appirio, Inc
 * Name         : ChildPhotoResult
 * Created By   : Karl Houseknecht (Appirio)
 * Purpose      : Web services for the Child Photo application
 * Created Date : 01/20/2017
 *
 * Date Modified                Modified By             Description of the update
  ----------------------------------------------------------------------------------------------------------
 * 01/20/2017                   Karl Houseknecht        Created
 **********************************************************************************************************/
global class ChildPhotoResult 
{
	webservice boolean Success;
	webservice string ErrorMessage;
	webservice string StackTrace;
}