/***********************************************************************************************************
 * Appirio, Inc
 * Name         : ChildPhotoMetadata
 * Created By   : Karl Houseknecht (Appirio)
 * Purpose      : Web services for the Child Photo application
 * Created Date : 01/20/2017
 *
 * Date Modified                Modified By             Description of the update
  ----------------------------------------------------------------------------------------------------------
 * 01/20/2017                   Karl Houseknecht        Created
 **********************************************************************************************************/
global class ChildPhotoMetadata 
{
	webservice string ParticipantId; 
	webservice string ParticipantNumber;
	webservice string ParticipantName;
	webservice string ParticipantShortName;
	webservice string NONumber;
	webservice string CommunityNumber;
	webservice string DOB;
	webservice string Gender;
	webservice string Narrative;
	webservice string LastPhotoDate;
	webservice string LastPhoto;
}