public with sharing class Constants {
    
    public static final String OPP_SOBJECT_TYPE = 'Opportunity';
    public static final String OPP_REC_TYPE_PROPOSAL = 'Proposal';
    public static final String PROJECT_SOBJECT_TYPE = 'Project__c';
    public static final String PROJECT_REC_TYPE_SINGLE_NO = 'Single_Country_Project';
    public static final String CASE_REC_TYPE_SIMPLE = '1 - Simple Case';
    public static final String CASE_REC_TYPE_STANDARD = '2 - Routed Case';
    public static final String CASE_REC_TYPE_NO = '3 - National Office Project Request';
    public static final String CASE_REC_TYPE_CHILD_INQ = '4 - National Office Participant Request';
    public static final String CASE_REC_TYPE_MASTER = 'X0_Master_Case';
    
    public static final String CASE_TAB = '/500/o';
    public static final String CONTACT_URL_PARM = 'def_contact_id';
    public static final String ACCOUNT_URL_PARM = 'def_account_id';
    public static final String NO_OVERRIDE = 'nooverride';
    public static final String RETURN_URL = 'retURL';
    
}