/***********************************************************************************************************
 * Appirio, Inc
 * Name         : EmailSubscriptionsInfo
 * Created By   : Karl Houseknecht (Appirio)
 * Purpose      : For ChildFund.org web services
 * Created Date : 03/24/2016
 *
 * Date Modified                Modified By             Description of the update
  ----------------------------------------------------------------------------------------------------------
 * 03/24/2016                   Karl Houseknecht        Created
 **********************************************************************************************************/
global class EmailSubscriptionsInfo 
{
	webservice integer ContId;
    webservice integer EpubId;
    webservice string Abbreviation;
    webservice string Description;
}