/***********************************************************************************************************
 * Appirio, Inc
 * Name         : FundProjectInfo
 * Created By   : Karl Houseknecht (Appirio)
 * Purpose      : For ChildFund.org web services
 * Created Date : 04/14/2016
 *
 * Date Modified                Modified By             Description of the update
  ----------------------------------------------------------------------------------------------------------
 * 04/14/2016                   Karl Houseknecht        Created
 **********************************************************************************************************/
global class FundProjectInfo 
{
    webservice integer Goal;
    webservice integer Raised;
    webservice integer Remaining;
}