/***********************************************************************************************************
 * Appirio, Inc
 * Name         : LTEOptInGlobalInfo
 * Created By   : Karl Houseknecht (Appirio)
 * Purpose      : For ChildFund.org web services
 * Created Date : 03/24/2016
 *
 * Date Modified                Modified By             Description of the update
  ----------------------------------------------------------------------------------------------------------
 * 03/24/2016                   Karl Houseknecht        Created
 **********************************************************************************************************/
global class LTEOptInGlobalInfo 
{
	webservice string Status;
    webservice integer Contactid;
    webservice boolean Isoptedin;
    webservice string Optindate;
}