/***********************************************************************************************************
 * Appirio, Inc
 * Name         : RefCodeInfo
 * Created By   : Karl Houseknecht (Appirio)
 * Purpose      : For ChildFund.org web services
 * Created Date : 02/24/2016
 *
 * Date Modified                Modified By             Description of the update
  ----------------------------------------------------------------------------------------------------------
 * 02/24/2016                   Karl Houseknecht        Created
 **********************************************************************************************************/
global class RefCodeInfo 
{
	webservice string errormessage;
    webservice string rvlowvalue;
    webservice string rvhighvalue;
    webservice string rvabbreviation;
    webservice string rvdomain;
    webservice string rvmeaning;
    webservice string rvtype;
    webservice integer id;
}