/***********************************************************************************************************
 * Appirio, Inc
 * Name         : TaxTotalInfo
 * Created By   : Karl Houseknecht (Appirio)
 * Purpose      : For ChildFund.org web services
 * Created Date : 03/11/2016
 *
 * Date Modified                Modified By             Description of the update
  ----------------------------------------------------------------------------------------------------------
 * 03/11/2016                   Karl Houseknecht        Created
 **********************************************************************************************************/
global class TaxTotalInfo 
{
	webservice string PreviousYearTotal;
    webservice string CurrentYearTotal;
}